# Generated by Django 5.0.3 on 2024-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="on_leave",
        ),
        migrations.AddField(
            model_name="doctor",
            name="on_leave",
            field=models.BooleanField(default=False),
        ),
    ]
