# Generated by Django 5.0.3 on 2024-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_appointment_on_leave_doctor_on_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
